export const ADD_TILE_DATA = "ADD_TILE_DATA"
export const LOAD_TILE_DATA = "LOAD_TILE_DATA"

export const LOADING_TILE_DATA = 'LOADING_TILE_DATA';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAIL = 'LOAD_DATA_FAIL';

export const ADDING_TILE_DATA = 'ADDING_TILE_DATA';
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS';
export const ADD_DATA_FAIL = 'ADD_DATA_FAIL';